
DROP TABLE Boss;
DROP TABLE Heal;
DROP TABLE Oruzje;
DROP TABLE Oklop;
DROP TABLE Modifier;
DROP TABLE Npc;
DROP TABLE Magije;


DROP TABLE Tip;
DROP TABLE Klase;
DROP TABLE Igra;



CREATE TABLE Igra (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ime VARCHAR2(30) NOT NULL
);

CREATE TABLE Klase (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vrsta VARCHAR2(30) NOT NULL
);

CREATE TABLE Boss (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igra NUMBER(10) NOT NULL,
    ime VARCHAR2(255) NOT NULL
);

CREATE TABLE Heal (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igra NUMBER(10) NOT NULL,
    ime VARCHAR2(30) NOT NULL
);

CREATE TABLE Oruzje (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igra NUMBER(10) NOT NULL,
    ime VARCHAR2(30) NOT NULL,
    klasa NUMBER(10) NOT NULL
);

CREATE TABLE Oklop (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igra NUMBER(10) NOT NULL,
    ime VARCHAR2(30) NOT NULL
);

CREATE TABLE Modifier (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igra NUMBER(10) NOT NULL,
    ime VARCHAR2(30) NOT NULL,
    tip NUMBER(10) NOT NULL
);

CREATE TABLE Npc (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igra NUMBER(10) NOT NULL,
    ime VARCHAR2(50) NOT NULL
);

CREATE TABLE Magije (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igra NUMBER(10) NOT NULL,
    ime VARCHAR2(30) NOT NULL,
    klasa NUMBER(10) NOT NULL
);

CREATE TABLE Tip (
    id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vrsta VARCHAR2(30) NOT NULL
);




ALTER TABLE Boss ADD CONSTRAINT Boss_fk1 FOREIGN KEY (igra) REFERENCES Igra(id);
ALTER TABLE Heal ADD CONSTRAINT Heal_fk1 FOREIGN KEY (igra) REFERENCES Igra(id);
ALTER TABLE Oruzje ADD CONSTRAINT Oruzje_fk1 FOREIGN KEY (igra) REFERENCES Igra(id);
ALTER TABLE Oruzje ADD CONSTRAINT Oruzje_fk3 FOREIGN KEY (klasa) REFERENCES Klase(id);
ALTER TABLE Oklop ADD CONSTRAINT Oklop_fk1 FOREIGN KEY (igra) REFERENCES Igra(id);
ALTER TABLE Modifier ADD CONSTRAINT Modifier_fk1 FOREIGN KEY (igra) REFERENCES Igra(id);
ALTER TABLE Modifier ADD CONSTRAINT Modifier_fk3 FOREIGN KEY (tip) REFERENCES Tip(id);
ALTER TABLE Npc ADD CONSTRAINT Npc_fk1 FOREIGN KEY (igra) REFERENCES Igra(id);
ALTER TABLE Magije ADD CONSTRAINT Magije_fk1 FOREIGN KEY (igra) REFERENCES Igra(id);
ALTER TABLE Magije ADD CONSTRAINT Magije_fk3 FOREIGN KEY (klasa) REFERENCES Klase(id);



INSERT INTO Igra (ime) VALUES ('Dark Souls 1');
INSERT INTO Igra (ime) VALUES ('Dark Souls 2');
INSERT INTO Igra (ime) VALUES ('Dark Souls 3');
INSERT INTO Igra (ime) VALUES ('Bloodborne');
INSERT INTO Igra (ime) VALUES ('Elden Ring');

select * from Igra

INSERT INTO Boss (igra, ime) VALUES (1, 'The Asylum Demon');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Taurus Demon');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Bell Gargoyle');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Moonlight Butterfly');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Capra Demon');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Gaping Dragon');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Stray Demon');
INSERT INTO Boss (igra, ime) VALUES (1, 'Chaos Witch Quelaag');
INSERT INTO Boss (igra, ime) VALUES (1, 'Ceaseless Discharge');
INSERT INTO Boss (igra, ime) VALUES (1, 'Great Grey Wolf Sif');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Iron Golem');
INSERT INTO Boss (igra, ime) VALUES (1, 'Crossbreed Priscilla');
INSERT INTO Boss (igra, ime) VALUES (1, 'Dragon Slayer Orenstein');
INSERT INTO Boss (igra, ime) VALUES (1, 'Executioner Smough');
INSERT INTO Boss (igra, ime) VALUES (1, 'Dark Sun Gwyndolin');
INSERT INTO Boss (igra, ime) VALUES (1, 'Pinwheel');
INSERT INTO Boss (igra, ime) VALUES (1, 'Gravelord Nito');
INSERT INTO Boss (igra, ime) VALUES (1, 'Seath the Scaleless');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Four Kings');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Demon Firesage');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Centipede Demon');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Bed of Chaos');
INSERT INTO Boss (igra, ime) VALUES (1, 'The Sanctuary Guardian');
INSERT INTO Boss (igra, ime) VALUES (1, 'Knight Artorias');
INSERT INTO Boss (igra, ime) VALUES (1, 'Black Dragon Kalameet');
INSERT INTO Boss (igra, ime) VALUES (1, 'Manus, Father of the Abyss');
INSERT INTO Boss (igra, ime) VALUES (1, 'Gwyn, Lord of Cinder');



INSERT INTO Boss (igra, ime) VALUES (2, 'Last Giant');
INSERT INTO Boss (igra, ime) VALUES (2, 'The Pursuer');
INSERT INTO Boss (igra, ime) VALUES (2, 'Iron Dragonslayer');
INSERT INTO Boss (igra, ime) VALUES (2, 'Dragonrider');
INSERT INTO Boss (igra, ime) VALUES (2, 'Flexile Sentry');
INSERT INTO Boss (igra, ime) VALUES (2, 'Ruin Sentinels');
INSERT INTO Boss (igra, ime) VALUES (2, 'Belfry Gargoyles');
INSERT INTO Boss (igra, ime) VALUES (2, 'The Lost Sinner');
INSERT INTO Boss (igra, ime) VALUES (2, 'Executioners Chariot');
INSERT INTO Boss (igra, ime) VALUES (2, 'Skeleton Lords');
INSERT INTO Boss (igra, ime) VALUES (2, 'Covetous Demon');
INSERT INTO Boss (igra, ime) VALUES (2, 'Mytha, Baneful Queen');
INSERT INTO Boss (igra, ime) VALUES (2, 'Royal Rat Vanguard');
INSERT INTO Boss (igra, ime) VALUES (2, 'The Rotten');
INSERT INTO Boss (igra, ime) VALUES (2, 'Scorpioness Najka');
INSERT INTO Boss (igra, ime) VALUES (2, 'Royal Rat Authority');
INSERT INTO Boss (igra, ime) VALUES (2, 'Prowling Magus and Congregation');
INSERT INTO Boss (igra, ime) VALUES (2, 'Dukes Dear Freya');
INSERT INTO Boss (igra, ime) VALUES (2, 'Smelter Demon');
INSERT INTO Boss (igra, ime) VALUES (2, 'Old Iron King');
INSERT INTO Boss (igra, ime) VALUES (2, 'Dragonriders');
INSERT INTO Boss (igra, ime) VALUES (2, 'Looking Glass Knight');
INSERT INTO Boss (igra, ime) VALUES (2, 'Demon of Song');
INSERT INTO Boss (igra, ime) VALUES (2, 'Velstadt the Royal Aegis');
INSERT INTO Boss (igra, ime) VALUES (2, 'Guardian Dragon');
INSERT INTO Boss (igra, ime) VALUES (2, 'Ancient Dragon');
INSERT INTO Boss (igra, ime) VALUES (2, 'Giant Lord');
INSERT INTO Boss (igra, ime) VALUES (2, 'Elena, Squallid Queen');
INSERT INTO Boss (igra, ime) VALUES (2, 'Sinh, the Slumbering Dragon');
INSERT INTO Boss (igra, ime) VALUES (2, 'Graverobber');
INSERT INTO Boss (igra, ime) VALUES (2, 'Ancient Soldier');
INSERT INTO Boss (igra, ime) VALUES (2, 'Cerah');
INSERT INTO Boss (igra, ime) VALUES (2, 'Smelter Demon II');
INSERT INTO Boss (igra, ime) VALUES (2, 'Fume Knight');
INSERT INTO Boss (igra, ime) VALUES (2, 'Sir Alonne');
INSERT INTO Boss (igra, ime) VALUES (2, 'Aava the Kings Pet');
INSERT INTO Boss (igra, ime) VALUES (2, 'Lud and Zallen');
INSERT INTO Boss (igra, ime) VALUES (2, 'Burnt Ivory King');
INSERT INTO Boss (igra, ime) VALUES (2, 'Darklurker');
INSERT INTO Boss (igra, ime) VALUES (2, 'Vendrick');
INSERT INTO Boss (igra, ime) VALUES (2, 'Throne Watcher and Defender');
INSERT INTO Boss (igra, ime) VALUES (2, 'Nashandra');
INSERT INTO Boss (igra, ime) VALUES (2, 'Aldia, Scholar of the First Sin');



INSERT INTO Boss (igra, ime) VALUES (3, 'Ludex Gundyr');
INSERT INTO Boss (igra, ime) VALUES (3, 'Vordt of the Boreal Valley');
INSERT INTO Boss (igra, ime) VALUES (3, 'Curse-Rotted Greatwood');
INSERT INTO Boss (igra, ime) VALUES (3, 'Crystal Sage');
INSERT INTO Boss (igra, ime) VALUES (3, 'Deacons Of The Deep');
INSERT INTO Boss (igra, ime) VALUES (3, 'Abyss Watchers');
INSERT INTO Boss (igra, ime) VALUES (3, 'High Lord Wolnir');
INSERT INTO Boss (igra, ime) VALUES (3, 'Old Demon King');
INSERT INTO Boss (igra, ime) VALUES (3, 'Pontiff Sulyvahn');
INSERT INTO Boss (igra, ime) VALUES (3, 'Yhorm, The Giant');
INSERT INTO Boss (igra, ime) VALUES (3, 'Aldrich, Devourer Of Gods');
INSERT INTO Boss (igra, ime) VALUES (3, 'Dancer Of The Boreal Valley');
INSERT INTO Boss (igra, ime) VALUES (3, 'Dragonslayer Armour');
INSERT INTO Boss (igra, ime) VALUES (3, 'Oceiros, The Consumed King');
INSERT INTO Boss (igra, ime) VALUES (3, 'Champion Gundyr');
INSERT INTO Boss (igra, ime) VALUES (3, 'Lorian, Elder Prince and Lothric, Younger Prince');
INSERT INTO Boss (igra, ime) VALUES (3, 'Ancient Wyvern');
INSERT INTO Boss (igra, ime) VALUES (3, 'Nameless King');
INSERT INTO Boss (igra, ime) VALUES (3, 'Soul Of Cinder');
INSERT INTO Boss (igra, ime) VALUES (3, 'Champion’s Gravetender and Gravetender Greatwolf');
INSERT INTO Boss (igra, ime) VALUES (3, 'Sister Friede');
INSERT INTO Boss (igra, ime) VALUES (3, 'Demon In Pain, Demon From Below, And Demon Prince');
INSERT INTO Boss (igra, ime) VALUES (3, 'Halflight, Spear Of The Church');
INSERT INTO Boss (igra, ime) VALUES (3, 'Darkeater Midir');
INSERT INTO Boss (igra, ime) VALUES (3, 'Slave Knight Gael');




INSERT INTO Boss (igra, ime) VALUES (4, 'Cleric Beast');
INSERT INTO Boss (igra, ime) VALUES (4, 'Father Gascoigne');
INSERT INTO Boss (igra, ime) VALUES (4, 'Blood Starved Beast');
INSERT INTO Boss (igra, ime) VALUES (4, 'Vicar Amelia');
INSERT INTO Boss (igra, ime) VALUES (4, 'Witch of Hemwick');
INSERT INTO Boss (igra, ime) VALUES (4, 'Shadow of Yharnam');
INSERT INTO Boss (igra, ime) VALUES (4, 'Rom, the Vacuous Spider');
INSERT INTO Boss (igra, ime) VALUES (4, 'Martyr Logarius');
INSERT INTO Boss (igra, ime) VALUES (4, 'Darkbeast Paarl');
INSERT INTO Boss (igra, ime) VALUES (4, 'The One Reborn');
INSERT INTO Boss (igra, ime) VALUES (4, 'Celestial Emissary');
INSERT INTO Boss (igra, ime) VALUES (4, 'Ebrietas, Daughter of the Cosmos');
INSERT INTO Boss (igra, ime) VALUES (4, 'Amygdala');
INSERT INTO Boss (igra, ime) VALUES (4, 'Micolash, Host of the Nightmare');
INSERT INTO Boss (igra, ime) VALUES (4, 'Mergo Wet Nurse');
INSERT INTO Boss (igra, ime) VALUES (4, 'Gehrman, the First Hunter');
INSERT INTO Boss (igra, ime) VALUES (4, 'Moon Presence');
INSERT INTO Boss (igra, ime) VALUES (4, 'Ludwig, the Holy Blade');
INSERT INTO Boss (igra, ime) VALUES (4, 'Orphan of Kos');
INSERT INTO Boss (igra, ime) VALUES (4, 'Lady Maria of the Astral Clocktower');
INSERT INTO Boss (igra, ime) VALUES (4, 'Living Failures');
INSERT INTO Boss (igra, ime) VALUES (4, 'Laurence, the First Vicar');





INSERT INTO Boss (igra, ime) VALUES (5, 'Margit the Fell Omen');
INSERT INTO Boss (igra, ime) VALUES (5, 'Godrick the Grafted');
INSERT INTO Boss (igra, ime) VALUES (5, 'Red Wolf of Radagon');
INSERT INTO Boss (igra, ime) VALUES (5, 'Rennala, Queen of the Full Moon');
INSERT INTO Boss (igra, ime) VALUES (5, 'Leonine Misbegotten');
INSERT INTO Boss (igra, ime) VALUES (5, 'Ancestor Spirit');
INSERT INTO Boss (igra, ime) VALUES (5, 'Starscourge Radahn');
INSERT INTO Boss (igra, ime) VALUES (5, 'Magma Wyrm Makar');
INSERT INTO Boss (igra, ime) VALUES (5, 'Mimic Tear');
INSERT INTO Boss (igra, ime) VALUES (5, 'Royal Knight Loretta');
INSERT INTO Boss (igra, ime) VALUES (5, 'Regal Ancestor Spirit');
INSERT INTO Boss (igra, ime) VALUES (5, 'Dragonkin Soldier of Nokstella');
INSERT INTO Boss (igra, ime) VALUES (5, 'Valiant Gargoyles');
INSERT INTO Boss (igra, ime) VALUES (5, 'Astel, Naturalborn of the Void');
INSERT INTO Boss (igra, ime) VALUES (5, 'Godskin Noble');
INSERT INTO Boss (igra, ime) VALUES (5, 'Rykard, Lord of Blasphemy');
INSERT INTO Boss (igra, ime) VALUES (5, 'Elemer of the Briar');
INSERT INTO Boss (igra, ime) VALUES (5, 'Godfrey, First Elden Lord');
INSERT INTO Boss (igra, ime) VALUES (5, 'Morgott the Omen King');
INSERT INTO Boss (igra, ime) VALUES (5, 'Mohg, the Omen');
INSERT INTO Boss (igra, ime) VALUES (5, 'Commander Niall');
INSERT INTO Boss (igra, ime) VALUES (5, 'Fire Giant');
INSERT INTO Boss (igra, ime) VALUES (5, 'Loretta, Knight of the Haligtree');
INSERT INTO Boss (igra, ime) VALUES (5, 'Malenia, Blade of Miquella');
INSERT INTO Boss (igra, ime) VALUES (5, 'Godskin Duo');
INSERT INTO Boss (igra, ime) VALUES (5, 'Dragonlord Placidusax');
INSERT INTO Boss (igra, ime) VALUES (5, 'Maliketh, the Black Blade');
INSERT INTO Boss (igra, ime) VALUES (5, 'Lichdragon Fortissax');
INSERT INTO Boss (igra, ime) VALUES (5, 'Mohg, Lord of Blood');
INSERT INTO Boss (igra, ime) VALUES (5, 'Hoarah Loux, Warrior');
INSERT INTO Boss (igra, ime) VALUES (5, 'Radagon of the Golden Order');
INSERT INTO Boss (igra, ime) VALUES (5, 'Elden Beast');




select * from Boss
select * from Boss where igra = 1
select * from Boss where igra = 2
select * from Boss where igra = 3
select * from Boss where igra = 4
select * from Boss where igra = 5




INSERT INTO Heal (igra, ime) VALUES (1, 'Estus Flask');
INSERT INTO Heal (igra, ime) VALUES (2, 'Estus Flask');
INSERT INTO Heal (igra, ime) VALUES (3, 'Estus Flask');
INSERT INTO Heal (igra, ime) VALUES (4, 'Blood Vial');
INSERT INTO Heal (igra, ime) VALUES (5, 'Flask of Crimson Tears');
INSERT INTO Heal (igra, ime) VALUES (5, 'Flask of Wondrous Physick');

select * from Heal








INSERT INTO Npc (igra, ime) VALUES (1, 'Alvina of the Darkroot Wood');
INSERT INTO Npc (igra, ime) VALUES (1, 'Anastacia of Astora');
INSERT INTO Npc (igra, ime) VALUES (1, 'Andre of Astora');
INSERT INTO Npc (igra, ime) VALUES (1, 'Big Hat Logan');
INSERT INTO Npc (igra, ime) VALUES (1, 'Black Iron Tarkus');
INSERT INTO Npc (igra, ime) VALUES (1, 'Blacksmith Vamos');
INSERT INTO Npc (igra, ime) VALUES (1, 'Crestfallen Merchant');
INSERT INTO Npc (igra, ime) VALUES (1, 'Crestfallen Warrior');
INSERT INTO Npc (igra, ime) VALUES (1, 'Crystal Knight');
INSERT INTO Npc (igra, ime) VALUES (1, 'Darkmoon Knightess');
INSERT INTO Npc (igra, ime) VALUES (1, 'Darkstalker Kaathe');
INSERT INTO Npc (igra, ime) VALUES (1, 'Daughter of Chaos');
INSERT INTO Npc (igra, ime) VALUES (1, 'Domhnall of Zena');
INSERT INTO Npc (igra, ime) VALUES (1, 'Dusk of Oolacile');
INSERT INTO Npc (igra, ime) VALUES (1, 'Eingyi');
INSERT INTO Npc (igra, ime) VALUES (1, 'Elizabeth');
INSERT INTO Npc (igra, ime) VALUES (1, 'Everlasting Dragon');
INSERT INTO Npc (igra, ime) VALUES (1, 'Giant Blacksmith');
INSERT INTO Npc (igra, ime) VALUES (1, 'Griggs of Vinheim');
INSERT INTO Npc (igra, ime) VALUES (1, 'Gwynevere, Princess of Sunlight');
INSERT INTO Npc (igra, ime) VALUES (1, 'Havel the Rock');
INSERT INTO Npc (igra, ime) VALUES (1, 'Hawkeye Gough');
INSERT INTO Npc (igra, ime) VALUES (1, 'Ingward');
INSERT INTO Npc (igra, ime) VALUES (1, 'Kingseeker Frampt');
INSERT INTO Npc (igra, ime) VALUES (1, 'Kirk, Knight of Thorns');
INSERT INTO Npc (igra, ime) VALUES (1, 'Knight Lautrec of Carim');
INSERT INTO Npc (igra, ime) VALUES (1, 'Laurentius of the Great Swamp');
INSERT INTO Npc (igra, ime) VALUES (1, 'Lords Blade Ciaran');
INSERT INTO Npc (igra, ime) VALUES (1, 'Maneater Mildred');
INSERT INTO Npc (igra, ime) VALUES (1, 'Marvellous Chester');
INSERT INTO Npc (igra, ime) VALUES (1, 'Oscar, Knight of Astora');
INSERT INTO Npc (igra, ime) VALUES (1, 'Oswald of Carim');
INSERT INTO Npc (igra, ime) VALUES (1, 'Paladin Leeroy');
INSERT INTO Npc (igra, ime) VALUES (1, 'Patches');
INSERT INTO Npc (igra, ime) VALUES (1, 'Petrus of Thorolund');
INSERT INTO Npc (igra, ime) VALUES (1, 'Quelaag Sister');
INSERT INTO Npc (igra, ime) VALUES (1, 'Quelana of Izalith');
INSERT INTO Npc (igra, ime) VALUES (1, 'Rhea of Thorolund');
INSERT INTO Npc (igra, ime) VALUES (1, 'Rickert of Vinheim');
INSERT INTO Npc (igra, ime) VALUES (1, 'Shiva of the East');
INSERT INTO Npc (igra, ime) VALUES (1, 'Shiva Bodyguard');
INSERT INTO Npc (igra, ime) VALUES (1, 'Sieglinde of Catarina');
INSERT INTO Npc (igra, ime) VALUES (1, 'Siegmeyer of Catarina');
INSERT INTO Npc (igra, ime) VALUES (1, 'Snuggly the Crow');
INSERT INTO Npc (igra, ime) VALUES (1, 'Solaire of Astora');
INSERT INTO Npc (igra, ime) VALUES (1, 'Undead Merchant Female');
INSERT INTO Npc (igra, ime) VALUES (1, 'Undead Merchant Male');
INSERT INTO Npc (igra, ime) VALUES (1, 'Undead Prince Ricard');
INSERT INTO Npc (igra, ime) VALUES (1, 'Vince And Nico Of Thorolund');
INSERT INTO Npc (igra, ime) VALUES (1, 'Witch Beatrice');
INSERT INTO Npc (igra, ime) VALUES (1, 'Xanthous King Jeremiah');



INSERT INTO Npc (igra, ime) VALUES (2, 'Aldia, Scholar of the First Sin');
INSERT INTO Npc (igra, ime) VALUES (2, 'Alsanna, Silent Oracle');
INSERT INTO Npc (igra, ime) VALUES (2, 'Belfry Guard');
INSERT INTO Npc (igra, ime) VALUES (2, 'Benhart of Jugo');
INSERT INTO Npc (igra, ime) VALUES (2, 'Blacksmith Lenigrast');
INSERT INTO Npc (igra, ime) VALUES (2, 'Blue Sentinel Targray');
INSERT INTO Npc (igra, ime) VALUES (2, 'Cale the Cartographer');
INSERT INTO Npc (igra, ime) VALUES (2, 'Captain Drummond');
INSERT INTO Npc (igra, ime) VALUES (2, 'Carhillion of the Fold');
INSERT INTO Npc (igra, ime) VALUES (2, 'Chancellor Wellager');
INSERT INTO Npc (igra, ime) VALUES (2, 'Creighton the Wanderer');
INSERT INTO Npc (igra, ime) VALUES (2, 'Cromwell the Pardoner');
INSERT INTO Npc (igra, ime) VALUES (2, 'Darkdiver Grandahl');
INSERT INTO Npc (igra, ime) VALUES (2, 'Emerald Herald');
INSERT INTO Npc (igra, ime) VALUES (2, 'Felkin the Outcast');
INSERT INTO Npc (igra, ime) VALUES (2, 'Grave Warden Agdayne');
INSERT INTO Npc (igra, ime) VALUES (2, 'Griant');
INSERT INTO Npc (igra, ime) VALUES (2, 'Head of Vengarl');
INSERT INTO Npc (igra, ime) VALUES (2, 'Housekeeper Milibeth');
INSERT INTO Npc (igra, ime) VALUES (2, 'Laddersmith Gilligan');
INSERT INTO Npc (igra, ime) VALUES (2, 'Licia of Lindeldt');
INSERT INTO Npc (igra, ime) VALUES (2, 'Lonesome Gavlan');
INSERT INTO Npc (igra, ime) VALUES (2, 'Loyce Knight');
INSERT INTO Npc (igra, ime) VALUES (2, 'Lucatiel of Mirrah');
INSERT INTO Npc (igra, ime) VALUES (2, 'Magerold of Lanafir');
INSERT INTO Npc (igra, ime) VALUES (2, 'Manscorpion Tark');
INSERT INTO Npc (igra, ime) VALUES (2, 'Maughlin the Armourer');
INSERT INTO Npc (igra, ime) VALUES (2, 'Merchant Hag Melentia');
INSERT INTO Npc (igra, ime) VALUES (2, 'Mild Mannered Pate');
INSERT INTO Npc (igra, ime) VALUES (2, 'Milfanito');
INSERT INTO Npc (igra, ime) VALUES (2, 'Morrel');
INSERT INTO Npc (igra, ime) VALUES (2, 'Rosabeth of Melfia');
INSERT INTO Npc (igra, ime) VALUES (2, 'Royal Sorcerer Navlaan');
INSERT INTO Npc (igra, ime) VALUES (2, 'Saulden, the Crestfallen Warrior');
INSERT INTO Npc (igra, ime) VALUES (2, 'Sparkling Sisters Dyna and Tillo');
INSERT INTO Npc (igra, ime) VALUES (2, 'Steady Hand McDuff');
INSERT INTO Npc (igra, ime) VALUES (2, 'Stone Trader Chloanne');
INSERT INTO Npc (igra, ime) VALUES (2, 'Straid of Olaphis');
INSERT INTO Npc (igra, ime) VALUES (2, 'Strowen');
INSERT INTO Npc (igra, ime) VALUES (2, 'Sweet Shalquoir');
INSERT INTO Npc (igra, ime) VALUES (2, 'The Rat King');
INSERT INTO Npc (igra, ime) VALUES (2, 'Titchy Gren');
INSERT INTO Npc (igra, ime) VALUES (2, 'Vendrick');
INSERT INTO Npc (igra, ime) VALUES (2, 'Weaponsmith Ornifex');

INSERT INTO Npc (igra, ime) VALUES (3, 'Fire Keeper');
INSERT INTO Npc (igra, ime) VALUES (3, 'Ludleth of Courland');
INSERT INTO Npc (igra, ime) VALUES (3, 'Andre of Astora');
INSERT INTO Npc (igra, ime) VALUES (3, 'Greirat of the Undead Settlement');
INSERT INTO Npc (igra, ime) VALUES (3, 'Yoel of Londor');
INSERT INTO Npc (igra, ime) VALUES (3, 'Yuria of Londor');
INSERT INTO Npc (igra, ime) VALUES (3, 'Anri of Astora');
INSERT INTO Npc (igra, ime) VALUES (3, 'Henriette');
INSERT INTO Npc (igra, ime) VALUES (3, 'Sirris of the Sunless Realms');
INSERT INTO Npc (igra, ime) VALUES (3, 'Karla');
INSERT INTO Npc (igra, ime) VALUES (3, 'Patches');
INSERT INTO Npc (igra, ime) VALUES (3, 'Lapp');
INSERT INTO Npc (igra, ime) VALUES (3, 'Orbeck of Vinheim');
INSERT INTO Npc (igra, ime) VALUES (3, 'Thomas');
INSERT INTO Npc (igra, ime) VALUES (3, 'Irina of Carim');
INSERT INTO Npc (igra, ime) VALUES (3, 'Emma, High Priestess of Lothric');
INSERT INTO Npc (igra, ime) VALUES (3, 'Blacksmith Andre');

INSERT INTO Npc (igra, ime) VALUES (4, 'Gehrman, the First Hunter');
INSERT INTO Npc (igra, ime) VALUES (4, 'Doll');
INSERT INTO Npc (igra, ime) VALUES (4, 'Father Gascoigne');
INSERT INTO Npc (igra, ime) VALUES (4, 'Lady Maria of the Astral Clocktower');
INSERT INTO Npc (igra, ime) VALUES (4, 'Alfred');
INSERT INTO Npc (igra, ime) VALUES (4, 'Eileen the Crow');
INSERT INTO Npc (igra, ime) VALUES (4, 'Gilbert');
INSERT INTO Npc (igra, ime) VALUES (4, 'Old Hunter');
INSERT INTO Npc (igra, ime) VALUES (4, 'Mensis Scholar');
INSERT INTO Npc (igra, ime) VALUES (4, 'Vicar Amelia');
INSERT INTO Npc (igra, ime) VALUES (4, 'Martyr Logarius');
INSERT INTO Npc (igra, ime) VALUES (4, 'The One Reborn');
INSERT INTO Npc (igra, ime) VALUES (4, 'Adella');
INSERT INTO Npc (igra, ime) VALUES (4, 'The Messenger');

INSERT INTO Npc (igra, ime) VALUES (5, 'Melina');
INSERT INTO Npc (igra, ime) VALUES (5, 'Blaidd');
INSERT INTO Npc (igra, ime) VALUES (5, 'Ranni the Witch');
INSERT INTO Npc (igra, ime) VALUES (5, 'Merchant Kalé');
INSERT INTO Npc (igra, ime) VALUES (5, 'Seluvis');
INSERT INTO Npc (igra, ime) VALUES (5, 'Fia');
INSERT INTO Npc (igra, ime) VALUES (5, 'Gideon Ofnir, the All-Knowing');
INSERT INTO Npc (igra, ime) VALUES (5, 'Albus');
INSERT INTO Npc (igra, ime) VALUES (5, 'Alexander the Iron Fist');
INSERT INTO Npc (igra, ime) VALUES (5, 'Blackguard Big Boggart');
INSERT INTO Npc (igra, ime) VALUES (5, 'Bloody Finger Hunter Yura');
INSERT INTO Npc (igra, ime) VALUES (5, 'Boc the Seamster');
INSERT INTO Npc (igra, ime) VALUES (5, 'Brother Corhyn');
INSERT INTO Npc (igra, ime) VALUES (5, 'D, Hunter of the Dead');
INSERT INTO Npc (igra, ime) VALUES (5, 'Diallos');
INSERT INTO Npc (igra, ime) VALUES (5, 'Edgar');
INSERT INTO Npc (igra, ime) VALUES (5, 'Enia, the Finger Reader');
INSERT INTO Npc (igra, ime) VALUES (5, 'Ensha of the Royal Remains');
INSERT INTO Npc (igra, ime) VALUES (5, 'Gatekeeper Gostoc');
INSERT INTO Npc (igra, ime) VALUES (5, 'Goldmask');
INSERT INTO Npc (igra, ime) VALUES (5, 'Gowry');
INSERT INTO Npc (igra, ime) VALUES (5, 'Gurranq, Beast Clergyman');
INSERT INTO Npc (igra, ime) VALUES (5, 'Hermit Merchant (Leyndell)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Hermit Merchant (Mountaintops East)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Hyetta');
INSERT INTO Npc (igra, ime) VALUES (5, 'Irina');
INSERT INTO Npc (igra, ime) VALUES (5, 'Isolated Merchant (Dragonbarrow)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Isolated Merchant (Raya Lucaria Academy)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Isolated Merchant (Weeping Peninsula)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Jar Bairn');
INSERT INTO Npc (igra, ime) VALUES (5, 'Jerren');
INSERT INTO Npc (igra, ime) VALUES (5, 'Kenneth Haight');
INSERT INTO Npc (igra, ime) VALUES (5, 'Knight Bernahl');
INSERT INTO Npc (igra, ime) VALUES (5, 'Latenna');
INSERT INTO Npc (igra, ime) VALUES (5, 'Melina');
INSERT INTO Npc (igra, ime) VALUES (5, 'Merchant Kalé');
INSERT INTO Npc (igra, ime) VALUES (5, 'Mohgwyn Palace');
INSERT INTO Npc (igra, ime) VALUES (5, 'Millicent');
INSERT INTO Npc (igra, ime) VALUES (5, 'Dung Eater');
INSERT INTO Npc (igra, ime) VALUES (5, 'Miriel, Pastor of Vows');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nepheli Loux');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nomadic Merchant (Caelid Highway North)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nomadic Merchant (Castle Morne Rampart)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nomadic Merchant (East Limgrave)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nomadic Merchant (Liurnia Lake Shore)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nomadic Merchant (Mt. Gelmir)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nomadic Merchant (North Limgrave)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nomadic Merchant (North Liurna)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nomadic Merchant (West Altus Plateau)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Nomadic Merchant (West Limgrave)');
INSERT INTO Npc (igra, ime) VALUES (5, 'Patches');
INSERT INTO Npc (igra, ime) VALUES (5, 'Pidia, Carian Servent');
INSERT INTO Npc (igra, ime) VALUES (5, 'Preceptor Seluvis');
INSERT INTO Npc (igra, ime) VALUES (5, 'Primeval Sorcerer Azur');
INSERT INTO Npc (igra, ime) VALUES (5, 'Ranni the Witch');
INSERT INTO Npc (igra, ime) VALUES (5, 'Renna');
INSERT INTO Npc (igra, ime) VALUES (5, 'Roderika');
INSERT INTO Npc (igra, ime) VALUES (5, 'Rya');
INSERT INTO Npc (igra, ime) VALUES (5, 'Shabriri');
INSERT INTO Npc (igra, ime) VALUES (5, 'Smithing Master Hewg');
INSERT INTO Npc (igra, ime) VALUES (5, 'Sorcerer Rogier');
INSERT INTO Npc (igra, ime) VALUES (5, 'Sorcerer Thops');
INSERT INTO Npc (igra, ime) VALUES (5, 'Sorceress Sellen');
INSERT INTO Npc (igra, ime) VALUES (5, 'Tanith');
INSERT INTO Npc (igra, ime) VALUES (5, 'Twin Maiden Husks');
INSERT INTO Npc (igra, ime) VALUES (5, 'War Counselor Iji');
INSERT INTO Npc (igra, ime) VALUES (5, 'White Mask Varré');






select * from Npc
select * from Npc where igra = 1
select * from Npc where igra = 2
select * from Npc where igra = 3
select * from Npc where igra = 4
select * from Npc where igra = 5


select * from Igra

